spring.application.name=firstjobApp

!spring.h2.console.enabled=true
!spring.h2.console.path=/h2-console
!spring.datasource.url=jdbc:h2:mem:test
!spring.datasource.driverClassName=org.h2.Driver
!spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
!spring.jpa.show-sql=true
!spring.jpa.hibernate.ddl-auto=update
!line no.  3 onward is  for setting up our database
!line no. 7 spring.jpa.database-platform is used to tell Hibernate which database-specific SQL dialect to use so that it can generate correct SQL queries and schema for that database.
!line no. 8 using because we want to see the query which are executing for our db
!line no. 9 using because we want to create table everytime we bring the application up and drop table everytime we shut down the application

!Actuator
!management.endpoints.web.exposure.include=*
!here instead of star we can also specify a specific endpoint that we want to display.
!line no. 16 is to expose all endpoint after adding this we can see a large number of endpoints of our application like beans  , metrics , scheduletask etc.
!management.endpoint.health.show-details=always
!line no. 19 is to expose all health actuator present at http://localhost:8080/actuator/health. health endpoint has 3 tag 1.component-> this will show whether application is properly up or not ,  which db we are using and that db is up or not. 2.diskspace-> info about disk space like total space , how much we are using , and how much is left. path of your project .3.ping-> represnt health status of ping component.

!management.info.env.enabled=true
!info.app.name=JobApplication
!info.app.description=job app built by anchal
!info.app.version=1.0.0
!line no. 22 23 24 25 is to expose all component of info endpoint.

!management.endpoint.shutdown.enabled=true
!to enable shutdown actuator.
!server.shutdown=graceful
!to enable gracefull shutdown

!to connect postgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobApp
!port 5432 is dafault port for postgresql
spring.datasource.username=anchal
spring.datasource.password=anchal
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
!here we are specifying dialect -> it is a configuration of sql generation and it can vary from database to database.
!in simple language it is like translator . means that every sql have syntax. they are trying to do same task but writing different query . so dialect just transform given query a standard SQL so that our applicatoin can understand what to do


!for eureka
!spring.application.name=Service-registry
!server.port=8761
!eureka.client.register-with-eureka=false
!use to specify that whether this application need to register itself with eureka ot not . here we are writing false because eureka doesnot need to register it self with eureka.
!eureka.client.fetch-registry=false
!use to specify whether this application need to fetch data from eureka . here we are writing false becuase eureka cannot fetch data from itself
!eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
!to tell the client ms that this is the server port/address of eureka  or we can say that this url is use to register our ms as a client

!spring.application.name=job-service
!use to give name to our ms.
