spring.application.name=firstjobApp
spring.datasource.url=jdbc:postgresql://localhost:5432/jobApp
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
